import Home from './Home';
import Profile from './ProfileScreen';
import AboutScreen from './AboutScreen';
import BookmarkScreen from './BookmarkScreen';
import DetailScreen from './DetailScreen';
import GalleryScreen from './GalleryScreen';
import Onboarding from './Onboarding';
import Discover from './Discover';
import AddBlogForm from './AddBlogForm';
import EditBlogForm from './EditBlogForm';
export {Home, AboutScreen, BookmarkScreen, DetailScreen, GalleryScreen, Onboarding, Discover, Profile, AddBlogForm,EditBlogForm};
